# Generated by Django 6.0.3 on 2026-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='application_status',
            field=models.CharField(choices=[('screening', 'Screening'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='screening', max_length=20),
        ),
    ]
