# Generated by Django 6.0.3 on 2026-03-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default='', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
