# Generated by Django 6.0.3 on 2026-03-26 13:02
"""
Purpose:
    Adds expected_salary field to Resume model.

Connects with:
    - Resume salary expectation data in DB/API layer
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
