# Generated by Django 6.0.3 on 2026-03-26 13:21
"""
Purpose:
    Adds expected_salary field to Candidate model.

Connects with:
    - Candidate profile data in DB/API layer
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_resume_expected_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
