# Generated by Django 6.0.3 on 2026-03-30 13:47
"""
Purpose:
    Creates DailyStats model for per-job daily application counts.

Connects with:
    - Celery periodic task generate_daily_stats in tasks.py
    - Admin reporting in admin.py
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_expected_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('application_count', models.PositiveIntegerField(default=0)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobposting')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('job_posting', 'date')},
            },
        ),
    ]
